# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_book(object):
    def setupUi(self, add_book):
        add_book.setObjectName("add_book")
        add_book.resize(465, 259)
        add_book.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.centralwidget = QtWidgets.QWidget(add_book)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 441, 51))
        font = QtGui.QFont()
        font.setFamily("MS Office Symbol Semilight")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(140, 90, 201, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 130, 126, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Office Symbol Semibold")
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        add_book.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(add_book)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        add_book.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(add_book)
        self.statusbar.setObjectName("statusbar")
        add_book.setStatusBar(self.statusbar)

        self.retranslateUi(add_book)
        QtCore.QMetaObject.connectSlotsByName(add_book)

    def retranslateUi(self, add_book):
        _translate = QtCore.QCoreApplication.translate
        add_book.setWindowTitle(_translate("add_book", "MainWindow"))
        self.label_3.setText(_translate("add_book", "Add a new Book to Library"))
        self.label_2.setText(_translate("add_book", "Book No."))
        self.pushButton.setText(_translate("add_book", "Add Book"))
        self.pushButton_2.setText(_translate("add_book", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_book = QtWidgets.QMainWindow()
    ui = Ui_add_book()
    ui.setupUi(add_book)
    add_book.show()
    sys.exit(app.exec_())
